version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: captainhook/captainhook
    versions:
    - 5.5.0
    - 5.5.1
    - 5.6.0
    - 5.6.1
    - 5.7.0
    - 5.8.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.73
    - 0.12.74
    - 0.12.79
    - 0.12.80
    - 0.12.82
    - 0.12.84
  - dependency-name: captainhook/plugin-composer
    versions:
    - 5.2.4
  - dependency-name: infection/infection
    versions:
    - 0.21.1
    - 0.21.3
  - dependency-name: bitexpert/captainhook-infection
    versions:
    - 0.2.0
