language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
  - php: 7.0
  - php: 7.1

before_script:
  - composer self-update
  - composer validate

script:
  - composer validate

