name: ci
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        magento: ['2.3.7-p2', '2.4.0', '2.4.1', '2.4.2', '2.4.3']
        coveralls: [ false ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'
            magento: '2.4.3'
            coveralls: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug
          extensions: bcmath, gd

      - name: Install Composer dependencies
        run: composer install

      - name: Install Magento 2.3.7-p2
        if: matrix.magento == '2.3.7-p2'
        run: composer update --with-dependencies magento/framework:102.0.7-p2 magento/module-webapi:100.4.0 infection/infection:0.22.0

      - name: Install Magento 2.4.0
        if: matrix.magento == '2.4.0'
        run: composer update --with-dependencies magento/framework:103.0.0 magento/module-webapi:100.4.0 infection/infection:0.22.0

      - name: Install Magento 2.4.1
        if: matrix.magento == '2.4.1'
        run: composer update --with-dependencies magento/framework:103.0.1 magento/module-webapi:100.4.0 infection/infection:0.22.0

      - name: Install Magento 2.4.2
        if: matrix.magento == '2.4.2'
        run: composer update --with-dependencies magento/framework:103.0.2 magento/module-webapi:100.4.1

      - name: Install Magento 2.4.3
        if: matrix.magento == '2.4.3'
        run: composer update --with-dependencies magento/framework:103.0.3 magento/module-webapi:100.4.2

      - name: Install Magerun
        if: matrix.coveralls == false
        run: |
          wget https://files.magerun.net/n98-magerun2-latest.phar
          mkdir -p ~/.n98-magerun2/modules
          ln -s $(pwd) ~/.n98-magerun2/modules/magerun2-list-api-endpoints
          php n98-magerun2-latest.phar help api:list:endpoints

      - name: Codesniffer
        run: composer cs-check

      - name: Static code analysis
        run: composer analyze

      - name: Unittests
        run: composer test
        if: matrix.coveralls == false

      - name: Infection for added files
        if: matrix.coveralls == true
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          ./vendor/bin/infection -j4 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered

      - name: Unittests with coverage
        if: matrix.coveralls == true
        run: composer coverage

      - name: Coveralls report
        if: matrix.coveralls == true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          ./vendor/bin/php-coveralls --coverage_clover=clover.xml -v
